// <auto-generated />
using System;
using Fitly.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fitly.API.Migrations
{
    [DbContext(typeof(FitlyDbContext))]
    [Migration("20260329150000_AddChibiSystem")]
    partial class AddChibiSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fitly.API.Models.Chibi", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("AccessoryItemId")
                    .HasColumnType("text");

                b.Property<string>("AuraEffectId")
                    .HasColumnType("text");

                b.Property<int>("ArmMuscle")
                    .HasColumnType("integer");

                b.Property<int>("CoreDefinition")
                    .HasColumnType("integer");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("CoreDefinition")
                    .HasColumnType("integer");

                b.Property<string>("HairColorId")
                    .HasColumnType("text");

                b.Property<DateTime>("LastBodyUpdateAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("OutfitItemId")
                    .HasColumnType("text");

                b.Property<int>("ShoulderWidth")
                    .HasColumnType("integer");

                b.Property<string>("SkinToneId")
                    .HasColumnType("text");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("UserId")
                    .HasColumnType("integer");

                b.Property<int>("WaistSize")
                    .HasColumnType("integer");

                b.Property<int>("LegMuscle")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("UserId")
                    .IsUnique();

                b.ToTable("Chibis");
            });

            modelBuilder.Entity("Fitly.API.Models.CosmeticItem", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("text");

                b.Property<string>("Category")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("CostPoints")
                    .HasColumnType("integer");

                b.Property<string>("Description")
                    .HasColumnType("text");

                b.Property<string>("ImageUrl")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<bool>("IsDefault")
                    .HasColumnType("boolean");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<string>("Rarity")
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)");

                b.HasKey("Id");

                b.HasIndex("Category");

                b.HasIndex("IsDefault");

                b.ToTable("CosmeticItems");
            });

            modelBuilder.Entity("Fitly.API.Models.PointsBalance", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("Balance")
                    .HasColumnType("integer");

                b.Property<int>("ChibiId")
                    .HasColumnType("integer");

                b.Property<int>("TotalEarned")
                    .HasColumnType("integer");

                b.Property<int>("TotalSpent")
                    .HasColumnType("integer");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("ChibiId")
                    .IsUnique();

                b.ToTable("PointsBalances");
            });

            modelBuilder.Entity("Fitly.API.Models.PointsTransaction", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("ChibiId")
                    .HasColumnType("integer");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Description")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<int>("Points")
                    .HasColumnType("integer");

                b.Property<string>("RelatedEntityId")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<string>("TransactionType")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.HasKey("Id");

                b.HasIndex("ChibiId", "CreatedAt");

                b.ToTable("PointsTransactions");
            });

            modelBuilder.Entity("Fitly.API.Models.UserCosmeticItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<DateTime>("AcquiredAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("ChibiId")
                    .HasColumnType("integer");

                b.Property<string>("CosmeticItemId")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<bool>("IsEquipped")
                    .HasColumnType("boolean");

                b.HasKey("Id");

                b.HasIndex("ChibiId", "IsEquipped");

                b.HasIndex("CosmeticItemId");

                b.ToTable("UserCosmeticItems");
            });

            // Foreign Key relationships
            modelBuilder.Entity("Fitly.API.Models.Chibi", b =>
            {
                b.HasOne("Fitly.API.Models.User", "User")
                    .WithOne("Chibi")
                    .HasForeignKey("Fitly.API.Models.Chibi", "UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
                b.Navigation("OwnedCosmetics");
                b.Navigation("PointsBalance");
                b.Navigation("PointsTransactions");
            });

            modelBuilder.Entity("Fitly.API.Models.PointsBalance", b =>
            {
                b.HasOne("Fitly.API.Models.Chibi", "Chibi")
                    .WithOne("PointsBalance")
                    .HasForeignKey("Fitly.API.Models.PointsBalance", "ChibiId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Chibi");
            });

            modelBuilder.Entity("Fitly.API.Models.PointsTransaction", b =>
            {
                b.HasOne("Fitly.API.Models.Chibi", "Chibi")
                    .WithMany("PointsTransactions")
                    .HasForeignKey("ChibiId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Chibi");
            });

            modelBuilder.Entity("Fitly.API.Models.UserCosmeticItem", b =>
            {
                b.HasOne("Fitly.API.Models.Chibi", "Chibi")
                    .WithMany("OwnedCosmetics")
                    .HasForeignKey("ChibiId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Fitly.API.Models.CosmeticItem", "CosmeticItem")
                    .WithMany("UserOwners")
                    .HasForeignKey("CosmeticItemId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Chibi");
                b.Navigation("CosmeticItem");
            });

            modelBuilder.Entity("Fitly.API.Models.Chibi", b =>
            {
                b.Navigation("OwnedCosmetics");
                b.Navigation("PointsBalance");
                b.Navigation("PointsTransactions");
            });

            modelBuilder.Entity("Fitly.API.Models.CosmeticItem", b =>
            {
                b.Navigation("UserOwners");
            });

            modelBuilder.Entity("Fitly.API.Models.User", b =>
            {
                b.Navigation("Chibi");
            });

#pragma warning restore 612, 618
        }
    }
}
